---
title: "eda"
author: "Marium Tapal"
output: html_document
---

```{r setup}
library(tidyverse)
library(plotly)
library(reshape2)
library(lubridate)
library(gganimate)
```

```{r load data}
social_media <- read_csv("~/Downloads/DC5-Data/Y*Int Social Media Data/YInt.csv") 
static_sensor_locations <- read_csv("~/Downloads/DC5-Data/Sensor Data and Maps/StaticSensorLocations.csv") 
static_sensor_readings <- read_csv("~/Downloads/DC5-Data/Sensor Data and Maps/StaticSensorReadings.csv") 
mobile_sensor_readings <- read_csv("~/Downloads/DC5-Data/Sensor Data and Maps/MobileSensorReadings.csv") 
mc1_reports_data <- read_csv("~/Downloads/DC5-Data/Damage Reports/mc1-reports-data.csv") %>% 
  mutate(location = as.factor(location))
```


```{r}
ggplot(mc1_reports_data, aes(x = time, y = shake_intensity)) + 
           geom_line() + 
           labs(title = "Overall Reported Shake Intensity in St. Himark",
                x = "Time", y = "Shake Intensity") + 
           theme_minimal() +
           theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

ggplotly(ggplot(mc1_reports_data, aes(x = time, y = shake_intensity)) + 
           geom_line() + 
           labs(title = "Reported Shake Intensity by Locations in St. Himark",
                x = "Time", y = "Shake Intensity") + 
           theme_minimal() +
           theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) + 
           facet_wrap(~location))
```

Location 3, 4, 12, 18 have the highest readings. Which corresponds to the map (StHimarkLabeledMap.png) where the quake was felt

# Heat Map

```{r}
# change data to long format for heat map
mc1_reports_data_long <- reshape2::melt(mc1_reports_data, id.vars = c("time", "location"))

# handling missing and repeated data
heat_map_data <- mc1_reports_data_long %>%
  group_by(time, location, variable) %>%
  mutate(value = round(mean(value, na.rm = TRUE), 2)) %>%
  unique()


# overall
ggplot(heat_map_data, aes(time, variable)) +
  geom_tile(aes(fill = value)) +
  scale_fill_gradient(low = "blue", high = "red") +
  labs(title = "Report Variables Over Time", x = "Time", y = "Report Variable", fill = "Value") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))


# by location
ggplot(heat_map_data, aes(time, variable)) +
  geom_tile(aes(fill = value)) +
  facet_wrap(~location) +
  scale_fill_gradient(low = "blue", high = "red") +
  labs(title = "Report Variables Over Time by Location", x = "Time", y = "Report Variable", fill = " Value") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

# by location
ggplot(heat_map_data, aes(time, location)) +
  geom_tile(aes(fill = value)) +
  scale_fill_gradient(low = "blue", high = "red") +
  labs(title = "Report Variables Over Time by Location", 
       x = "Time", y = "Location", fill = " Value") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

# by variable
ggplot(heat_map_data, aes(time, location)) +
  geom_tile(aes(fill = value)) +
  facet_wrap(~variable) +
  scale_fill_gradient(low = "blue", high = "red") +
  labs(title = "Location Over Time by Report Variables", 
       x = "Time", y = "Location", fill = " Value") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

